# .github/workflows/macos.yml
name: Build macOS DMG and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0, v1.2.3
  workflow_dispatch: # Allows manual runs from the Actions tab

jobs:
  build-and-release:
    runs-on: macos-latest # Use the latest available macOS runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 pandas Pillow
          pip install pyinstaller==6.8.0

      - name: Create .icns from .png (Robust Method)
        run: |
          python -c "
          from PIL import Image
          import os

          source_image = 'icon.png'
          iconset_dir = 'icon.iconset'
          os.makedirs(iconset_dir, exist_ok=True)

          img = Image.open(source_image)
          sizes = [16, 32, 128, 256, 512]

          for size in sizes:
              # Standard icon
              resized_img = img.resize((size, size), Image.Resampling.LANCZOS)
              resized_img.save(os.path.join(iconset_dir, f'icon_{size}x{size}.png'))
              
              # Retina icon (@2x)
              resized_img_retina = img.resize((size * 2, size * 2), Image.Resampling.LANCZOS)
              resized_img_retina.save(os.path.join(iconset_dir, f'icon_{size}x{size}@2x.png'))

          print('Iconset created successfully.')
          "
          iconutil -c icns icon.iconset -o app_icon.icns

      - name: Build macOS App with PyInstaller
        run: |
          pyinstaller Tagger.py \
            --name "SF Tagger" \
            --onefile \
            --windowed \
            --icon="app_icon.icns" \
            --collect-data pandas # <-- THIS IS THE FIX

      - name: Create DMG
        run: |
          brew install create-dmg
          
          mkdir -p dmg_assets
          mv "dist/SF Tagger" dmg_assets/
          
          create-dmg \
            --volname "SF Tagger Installer" \
            --window-pos 200 120 \
            --window-size 600 380 \
            --icon-size 100 \
            --icon "SF Tagger" 150 190 \
            --app-drop-link 450 190 \
            "SF_Tagger_macOS.dmg" \
            "dmg_assets/"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: SF_Tagger_macOS.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
