name: macos-build-dmg-unsigned

on:
  push:
    tags: ["v*.*.*"]     # push a tag like v1.0.0 to trigger
  workflow_dispatch:

jobs:
  build:
    # Build for both Apple Silicon and Intel (two DMGs)
    strategy:
      matrix:
        runner: [macos-14, macos-13]   # 14=arm64, 13=x86_64
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements
          pip install pyinstaller create-dmg

      # Optional: convert assets/icon.png -> assets/icon.icns if PNG exists
      - name: Generate .icns (optional)
        run: |
          if [ -f "assets/icon.png" ]; then
            mkdir -p icon.iconset
            # create standard sizes from base icon.png (1024x1024 recommended)
            for s in 16 32 64 128 256 512; do
              /usr/bin/sips -z $s $s assets/icon.png --out icon.iconset/icon_${s}x${s}.png > /dev/null
              /usr/bin/sips -z $((s*2)) $((s*2)) assets/icon.png --out icon.iconset/icon_${s}x${s}@2x.png > /dev/null
            done
            /usr/bin/iconutil -c icns icon.iconset -o assets/icon.icns
            rm -rf icon.iconset
          fi

      - name: Build .app with PyInstaller
        run: |
          ICON_FLAG=""
          if [ -f "assets/icon.icns" ]; then ICON_FLAG="--icon assets/icon.icns"; fi
          pyinstaller Tagger.py \
            --name "SF Tagger" \
            --windowed \
            $ICON_FLAG \
            --noconfirm \
            --collect-all PySide6 \
            --collect-data pandas

      - name: Create unsigned DMG
        run: |
          create-dmg "dist/SF_Tagger-${{ matrix.runner }}.dmg" "dist/SF Tagger.app" \
            --volname "SF Tagger" \
            --window-size 600 400 \
            --icon-size 96 \
            --app-drop-link 425 205

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: SF_Tagger_${{ matrix.runner }}
          path: dist/SF_Tagger-${{ matrix.runner }}.dmg
